import {createI18n} from "vue-i18n";

const messages = {
  EN: {
    todo: {
      placeholder: "Add task",
      title: 'What you have to do today',
    },
    appbar: {
      todo: "ToDo List",
      about: 'About',
      home: 'Home',
      projectName: 'Project',
      subtitle: 'Homework'
    },
    buttons: {
      clickme: "Click me"
    },
    about: {
      title: "About Page",
      description: "We are a dynamic team of passionate individuals dedicated to creating unique solutions for our clients. Our company was founded with the goal of providing innovative products and services that exceed our clients' expectations.\n" +
        "\n" +
        "Our mission is to inspire and facilitate the growth of our clients by using the latest technologies and creative approaches. Our experienced professionals from various fields work with full commitment to deliver solutions that are not only effective, but also aesthetically and functionally excellent.\n" +
        "\n" +
        "We believe in a partnership model of cooperation, where our successes are shared. That is why we focus on open communication and close cooperation with our clients. Our projects are created according to the individual needs and goals of the client, always with the highest quality standards.\n" +
        "\n" +
        "We constantly follow the latest trends and innovations in our industry to provide our clients with solutions that are fully compliant with current standards. This allows us to provide products and services that are not only modern, but also future-proof.\n" +
        "\n" +
        "We invite you to work with us and join the ranks of satisfied customers. Together we can achieve success and innovate to change the world. Contact us today to start creating something unique!\n" +
        "\n"
    },
    article: {
      descriptionShort: "ChatGPT is an advanced language model based on the GPT-3.5 architecture, developed by OpenAI. It utilizes machine learning to generate human-like responses to given text or questions. The operation of this model can be divided into three main stages: input data processing, generating contextual understanding, and creating responses. Before generating a response, the input data is processed by the model. This may involve text tokenization, which means dividing it into smaller units such as words or characters for better understanding of the context. The model processes these units and represents them as numbers that can be analyzed and manipulated. Once the input data is processed, ChatGPT proceeds to generate contextual understanding based on the available knowledge. The model analyzes the input text, taking into account the context and relevant information to better understand the intent and meaning of the question...........................",
      title: "How does ChatGPT work? - Discover the secrets of the advanced language model",
      text: "ChatGPT is an advanced language model based on the GPT-3.5 architecture, developed by OpenAI. It uses machine learning to generate human-like responses to given content or questions. The operation of this model can be divided into three main stages: processing input data, generating contextual understanding and creating responses.\n" +
        "\n" +
        "1. Input processing:\n" +
        "Before generating a response, the input data is processed by the model. This may include tokenization of the text, which is the division of the text into smaller units, such as words or characters, in order to better understand the context. The model processes these units and represents them as numbers that can be analyzed and manipulated.\n" +
        "\n" +
        "2. Generate contextual understanding:\n" +
        "Once the input is processed, ChatGPT proceeds to generate contextual understanding based on the available knowledge. The model analyzes the input text, taking into account the context and related information to better understand the intent and meaning of the question. It uses a huge amount of training data, which includes a variety of information sources such as articles, books, websites and more.\n" +
        "\n" +
        "3. Create answers:\n" +
        "Once the model has an understanding of the context, it moves on to generating an answer. It uses its knowledge and language skills to generate a logical and appropriate response to the question or content asked. The model tries to replicate people's style, tone and expression to ensure the most realistic interactions possible.\n" +
        "\n" +
        "It is important to note that ChatGPT is entirely machine learning and has no real understanding or awareness. The responses generated by the model are the result of analyzing language patterns in the training data and attempting to generate responses based on those patterns. ChatGPT does not have its own opinion or ability to generate information on its own beyond what it has learned from the available data.\n" +
        "\n" +
        "While ChatGPT can be extremely helpful as a tool for generating content, answering questions and assisting with various language tasks, caution should be exercised regarding the information generated by the language models. Verification and confirmation of information from various sources is always important to ensure accuracy and reliability.\n"
    }
  },

  PL: {
    todo: {
      placeholder: "Dodaj zadanie",
      title: 'Co masz dziś do zrobienia',
    },
    appbar: {
      todo: "Lista rzeczy do zrobienia",
      about: 'O nas',
      home: 'Strona główna',
      projectName: 'Projekt',
      subtitle: 'Praca domowa'
    },
    buttons: {
      clickme: "Kliknij"
    },
    about: {
      title: "O nas",
      description: "          Jesteśmy dynamicznym zespołem pasjonatów, którzy poświęcają się tworzeniu unikalnych rozwiązań dla naszych klientów. Nasza firma powstała z myślą o dostarczaniu innowacyjnych produktów i usług, które przekraczają oczekiwania naszych klientów.\n" +
        "\n" +
        "          Nasza misja to inspirować i ułatwiać rozwój naszych klientów poprzez wykorzystanie najnowszych technologii i kreatywnego podejścia. Nasi doświadczeni specjaliści z różnych dziedzin pracują z pełnym zaangażowaniem, aby dostarczyć rozwiązania, które są nie tylko efektywne, ale także estetycznie i funkcjonalnie doskonałe.\n" +
        "\n" +
        "          Wierzymy w partnerski model współpracy, gdzie nasze sukcesy są wspólne. Dlatego stawiamy na otwartą komunikację i bliską współpracę z naszymi klientami. Nasze projekty są tworzone zgodnie z indywidualnymi potrzebami i cele klienta, zawsze z zachowaniem najwyższych standardów jakości.\n" +
        "\n" +
        "          Nieustannie podążamy za najnowszymi trendami i innowacjami w naszej branży, aby zapewnić naszym klientom rozwiązania, które są w pełni zgodne z obecnie panującymi standardami. Dzięki temu możemy dostarczać produkty i usługi, które są nie tylko nowoczesne, ale również przyszłościowe.\n" +
        "\n" +
        "          Zapraszamy do współpracy z nami i dołączania do grona zadowolonych klientów. Razem możemy osiągnąć sukces i wprowadzić innowacje, które zmienią świat. Skontaktuj się z nami już dziś, aby zacząć tworzyć coś wyjątkowego!"
    },
    article: {
      descriptionShort: "ChatGPT to zaawansowany model językowy oparty na architekturze GPT-3.5, opracowany przez OpenAI. Wykorzystuje on uczenie maszynowe, aby generować ludzko-podobne odpowiedzi na zadaną mu treść lub pytania. Działanie tego modelu można podzielić na trzy główne etapy: przetwarzanie danych wejściowych, generowanie kontekstowego zrozumienia i tworzenie odpowiedzi. Przed rozpoczęciem generowania odpowiedzi, dane wejściowe są przetwarzane przez model. Może to obejmować tokenizację tekstu, czyli podział go na mniejsze jednostki, takie jak słowa lub znaki, w celu lepszego zrozumienia kontekstu. Model przetwarza te jednostki i reprezentuje je jako liczby, które można analizować i manipulować. Kiedy dane wejściowe są przetworzone, ChatGPT przystępuje do generowania kontekstowego zrozumienia na podstawie dostępnej wiedzy. Model analizuje tekst wejściowy, uwzględniając kontekst i związane informacje, aby lepiej zrozumieć intencję i znaczenie pytania.........",
      title: "Jak działa ChatGPT? - Odkryj tajemnice zaawansowanego modelu językowego",
      text: "ChatGPT to zaawansowany model językowy oparty na architekturze GPT-3.5, opracowany przez OpenAI. Wykorzystuje on uczenie maszynowe, aby generować ludzko-podobne odpowiedzi na zadaną mu treść lub pytania. Działanie tego modelu można podzielić na trzy główne etapy: przetwarzanie danych wejściowych, generowanie kontekstowego zrozumienia i tworzenie odpowiedzi. Przed rozpoczęciem generowania odpowiedzi, dane wejściowe są przetwarzane przez model. Może to obejmować tokenizację tekstu, czyli podział go na mniejsze jednostki, takie jak słowa lub znaki, w celu lepszego zrozumienia kontekstu. Model przetwarza te jednostki i reprezentuje je jako liczby, które można analizować i manipulować. Kiedy dane wejściowe są przetworzone, ChatGPT przystępuje do generowania kontekstowego zrozumienia na podstawie dostępnej wiedzy. Model analizuje tekst wejściowy, uwzględniając kontekst i związane informacje, aby lepiej zrozumieć intencję i znaczenie pytania. Wykorzystuje on ogromną ilość danych treningowych, które obejmują różnorodne źródła informacji, takie jak artykuły, książki, strony internetowe i wiele innych. Gdy model ma już zrozumienie kontekstu, przechodzi do generowania odpowiedzi. Wykorzystuje swoją wiedzę i zdolności językowe, aby wygenerować logiczną i odpowiednią odpowiedź na zadane pytanie lub treść. Model stara się odwzorować styl, ton i sposób wyrażania ludzi, aby zapewnić jak najbardziej realistyczne interakcje. Ważne jest zaznaczyć, że ChatGPT jest w pełni uczenia maszynowego i nie posiada rzeczywistego zrozumienia lub świadomości. Odpowiedzi generowane przez model są wynikiem analizy wzorców językowych w danych treningowych i próby generowania odpowiedzi na podstawie tych wzorców. ChatGPT nie posiada własnej opinii ani zdolności do samodzielnego generowania informacji poza tym, czego nauczył się na podstawie dostępnych danych. Chociaż ChatGPT może być niezwykle pomocny jako narzędzie do generowania treści, udzielania odpowiedzi na pytania i pomocy w różnych zadaniach językowych, należy zachować ostrożność w odniesieniu do informacji generowanych przez modele językowe. Weryfikacja i potwierdzenie informacji z różnych źródeł zawsze są ważne, aby zapewnić dokładność i wiarygodność."
    }
  }
}


const i18n = createI18n({
  locale: 'PL',
  fallbackLocale: 'EN',
  messages
})
export default i18n
